sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-german latex-beamer
  git
- git clone https://github.com/matze/mtheme.git
- cd mtheme
- make sty
- cp *.sty ../
- cd ../
script:
- pdflatex IT-Sicherheit.tex
- pdflatex IT-Sicherheit.tex 
- pdflatex IT-Sicherheit_article.tex
- pdflatex IT-Sicherheit_article.tex
deploy:
  provider: releases
  api_key:
    secure: U+KwG1oSjqg9l+06kYWEdiq7kwtlLbFmwS5X998qRze/SfAJ8K9RnXLj1Dg7PfF846yfedZ/AD/PR0uc5OEAGvDIwoH+dej4qgxpU0OwBM3ECGVn5n5ct3z$
  file:
    - IT-Sicherheit.pdf
    - IT-Sicherheit_article.pdf
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: mflingelli/IT-Sicherheit
    branch: master

