sudo: required
language: ruby
dist: xenial
before_install:
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-german
  latex-beamer git
- git clone https://github.com/matze/mtheme.git
- cd mtheme
- make sty
- cp *.sty ../
- cd ../
script:
- pdflatex IT-Sicherheit.tex
- pdflatex IT-Sicherheit.tex
- pdflatex IT-Sicherheit_article.tex
- pdflatex IT-Sicherheit_article.tex
deploy:
  provider: releases
  user: mflingelli
  file:
  - IT-Sicherheit.pdf
  - IT-Sicherheit_article.pdf
  skip_cleanup: true
  draft: false
  prerelease: true
  overwrite: true
  on:
    tags: true
    repo: mflingelli/IT-Sicherheit
    branch: master
  password:
    secure: Hve7yO29lJQdkAnj/RVnWcZ/vTJ7GbYPfO0L8hqqYgy1GTf/DHWIZQ5IOSk/A8tBsPJcFFlyEqUaPMdXp2s4cxJLYKKeHE9BubZZfMnvsERRTa5siZorNWMT+WPe8N/h2Df3uxghaUhVvfHPrHn4zqwp4TL+iLYwGi9Y8R/fFpSExYWqSC8HrnuL7xf1eqfqGCYiQnLp3BOXgZUzPzsMf9Smw02saCVc2jhaG7TtdJF6Vs+mPNRLBlw4XGhautsQzh7QT4mz2eppAKPZ1Zcdru1gWI7wYLWJ+vMVCsK6UOMfN2Purc5Z3RJeqHZc5jTZDrGrmmJtbWALbvuxuGbRW5RJ0K9StBKkRkn1oeyI2VyYIdCYrJhmTj/qmc+YaO1Ne8PthZXrzIsXtu0eojIxfNituRjPpunh696C6TAtkDwni7J65GhX8pJx1M7Vog4GRnaRWE5F2KlUi/I+15KVGtt+nQzvPy4A1CVRTJcLFjj687/evqyX2P4J62d1QrJc1VCMTYk6lB+TTiDJGDLhDJAEasMwdcEfM56SjQpYXeBGu+WPMKkopqu+GpY7+QNVz3yR3+myw+rrzwfAXFDP9lueLmvLez225NgQqN5Lrop8dR83xXxkquMHAvoO6L8c/rPTuR1o8jkasgPy72EsK8jPbK4mi7qVDc11+JUJdVE=
